POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento 4",
    "details": null,
    "maximumAttendees": 122
}

###

POST http://localhost:3333/events/217a2695-0e5b-4c47-83cc-f60863ec8d08/attendees
Content-Type: application/json

{
    "name": "Kelvin Nicolau",
    "email": "kelvinnicolau7@gmail.com"
}

###

GET http://localhost:3333/events/217a2695-0e5b-4c47-83cc-f60863ec8d08

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/217a2695-0e5b-4c47-83cc-f60863ec8d08/attendees?query=kelvin

###
 